[theme]
primaryColor="#1E88E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8F8F8"
textColor="#000000"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false

[global]
disableWatchdogWarning=true
